### ISSUE TITLE
Release v4.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-entity-audit#182]
@deepu105 I can do the release if give the rights.

**Comment by Ebsan** [comment]
Any updates on the next release? We could really use this and not having it in npmjs.org is causing some weird issues when building locally.

**Comment by mshima** [comment]
@DanielFran do you have release permission?

**Comment by DanielFran** [comment]
@mshima not for this project. @pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
@DanielFran : you are owner of jhipster team in NPM, you should be able to config what you want there

From what I see, the last release of this package was 3 years ago, so you need to:
- create a specific team in NPM orga
- add the member on this, specially @mshima 
- and link this team to this npm repo

@DanielFran : simpler solution would be to publish directly to NPM, as you have the permissions

![image](https://user-images.githubusercontent.com/9156882/201889798-f631a599-7688-4611-987b-a6de29db9566.png)

**Comment by shanewow** [comment]
+1

**Comment by DanielFran** [comment]
@pascalgrimaud We should transfer first this project to Jhipster organisation?

**Comment by pascalgrimaud** [comment]
@DanielFran : maybe, but I never use this project
The initial commit was done by @deepu105 so he's the one who should do it

**Comment by deepu105** [comment]
Sure I'll transfer the project

**Comment by deepu105** [comment]
I have transfered the project. Let me know if you face any issue

**Comment by shanewow** [comment]
@mshima Do you know when we should expect a release? Ty!

**Comment by mshima** [comment]
@deepu105 @DanielFran maybe you can give me publish rights?

**Comment by DanielFran** [comment]
@mshima Can you confirm you have access now?

**Comment by mshima** [comment]
Thanks @DanielFran. looks like I have:
<img width="460" alt="Captura de Tela 2023-02-03 às 14 25 02" src="https://user-images.githubusercontent.com/1417183/216667793-82dd3d9d-0c02-4f33-be26-81057b846280.png">

I will create the release soon.

We should deprecate and archive the generator-jhipster-(modules/blueprint) packages.

**Comment by mshima** [comment]
Released.
