### ISSUE TITLE
Blueprint custom CLI `jhipster-my-blueprint` not found

### ISSUE THREAD

**Issue by istibekesi** [jhipster/generator-jhipster-entity-audit#183]
Following the steps written in the readme, after npm install:
`jhipster-entity-audit: command not found`

Alternative `jhipster --blueprints entity-audit` does not work either: 
`this.registerPrettierTransform is not a function`

I have the latest `v3.3.0`. According to previously closed issues, both problem supposed to be fixed in this version, right?

**Comment by mshima** [comment]
No next release only.
You can install from git following https://github.com/hipster-labs/generator-jhipster-entity-audit#pre-release.
v4 release with the reimplementation is pending

**Comment by mshima** [comment]
Version v4.0.0 is released, closing.
