### ISSUE TITLE
Audits is not showed when at least one action is DELETE

### ISSUE THREAD

**Issue by edilsonmendes** [jhipster/generator-jhipster-entity-audit#190]
Audits is not showed when at least one action is DELETE. In the console we could see a Json parse error. 
![audit-delete-error](https://user-images.githubusercontent.com/27703772/202787416-e29deee6-7385-455f-b4e4-ce131509b643.jpeg)

The error seems to be on line 53 of the file generators/angular-audit/templates/src/main/webapp/app/admin/entity-audit/entity-audit.component.ts.ejs. Instead of `it.entityValue = JSON.parse(it.entityValue ?? '');` it could be `it.entityValue = JSON.parse(it.entityValue ?? '{}');` 

The same error on line 54 of generators/angular-audit/templates/src/main/webapp/app/admin/entity-audit/entity-audit-modal.component.ts.ejs

**Comment by mshima** [comment]
Fixed in v4.0.0
