### ISSUE TITLE
`jhipster --blueprints entity-audit` NOT WORKING in JHipster versions >= 7

### ISSUE THREAD

**Issue by gitbusycoding** [jhipster/generator-jhipster-entity-audit#192]
jhipster@3c559fd6ef3d:~/app/member-dm$ jhipster --blueprints entity-audit
INFO! Switching to JHipster installed locally in current project's node repository (node_modules)
INFO! No custom sharedOptions found within blueprint: generator-jhipster-entity-audit at /home/jhipster/app/member-dm/node_modules/generator-jhipster-entity-audit
INFO! No custom commands found within blueprint: generator-jhipster-entity-audit at /home/jhipster/app/member-dm/node_modules/generator-jhipster-entity-audit
(node:171) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at /home/jhipster/app/member-dm/node_modules/yeoman-environment/package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v7.9.3

     info Using blueprint generator-jhipster-entity-audit for app subgenerator
(node:171) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./generators/" in the "exports" field module resolution of the package at /home/jhipster/app/member-dm/node_modules/generator-jhipster/package.json.
Update this package.json to use a subpath pattern like "./generators/*".
✖ An error occured while running jhipster-entity-audit:app#init
ERROR! this.registerPrettierTransform is not a function
TypeError: this.registerPrettierTransform is not a function
    at module.exports.init (/home/jhipster/app/member-dm/node_modules/generator-jhipster-entity-audit/generators/app/index.js:23:14)
    at Object.<anonymous> (/home/jhipster/app/member-dm/node_modules/yeoman-generator/lib/index.js:1091:23)
    at /home/jhipster/app/member-dm/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/jhipster/app/member-dm/node_modules/run-async/index.js:26:19
    at /home/jhipster/app/member-dm/node_modules/yeoman-generator/lib/index.js:1092:9
    at new Promise (<anonymous>)
    at module.exports.executeTask (/home/jhipster/app/member-dm/node_modules/yeoman-generator/lib/index.js:1063:12)
    at runLoop.add.once (/home/jhipster/app/member-dm/node_modules/yeoman-generator/lib/index.js:1043:14)
    at Immediate.<anonymous> (/home/jhipster/app/member-dm/node_modules/grouped-queue/lib/subqueue.js:48:34)

**Comment by mshima** [comment]
VersVersion v4.0.0 is released.
There is no reproduction steps, closing.
