### ISSUE TITLE
When I run pre-release version of entity-audit on Jhipster v7.9.3 with Angular, EntityNavbarItems and RouterModule are getting empty

### ISSUE THREAD

**Issue by vikram-vst** [jhipster/generator-jhipster-entity-audit#194]
![image](https://user-images.githubusercontent.com/10498807/216572543-75c01f13-ac5c-4054-8050-9df1f2a25297.png)
![image](https://user-images.githubusercontent.com/10498807/216572660-022d6701-5847-4554-bdff-5e033cad3a7d.png)

Dropdown menu is also gone:
![image](https://user-images.githubusercontent.com/10498807/216576171-6cac5519-99b5-48a4-b733-d7286ae5564d.png)

**Comment by mshima** [comment]
You need to provide a way to reproduce.
But probably it's missing `--with-entities` at regeneration.

Closing, we can reopen if reproduction steps are available.
