### ISSUE TITLE
Entity Audit not working using jdl file without application but only with Entities

### ISSUE THREAD

**Issue by peppevaccaro** [jhipster/generator-jhipster-entity-audit#197]
Hi, 
we installed the Entity Audit in a Jhipster project and we are using different jdl files, one containing the definition of the applications and one containing the entities.

We noticed that executing the jdl command, using the jdl file attached containing only the entities, the entities are created correctly, but nothing about the Entity Audit is generated (for example extends AbstractAuditingEntity<Long>).

The JDL file we are using contains the following code:

      @EnableAudit
      entity Client{
          nome String required
          adClient Long required
      }
      
      relationship ManyToMany {
          Client{user} to User
      }
      
      paginate Client with pagination
      
      // Use Data Transfer Objects (DTO)
      dto Client with mapstruct
      
      // Set service options to all except few
      service Client with serviceClass
      
      filter Client
      readOnly Client

It seems that it does not start with the creation of entities only but only with the creation of applications, in fact using the following jdl instead, the Entity Audit works correctly:

       application {
      config {
        applicationType monolith
        cacheProvider no
        creationTimestamp 1632872179205
        devDatabaseType h2Disk
        enableHibernateCache false
        enableTranslation false
        testFrameworks [cypress]
      }
    
      entities Blog, Post, Tag
    }
    
    @EnableAudit
    entity Blog {
      name String required minlength(3)
      handle String required minlength(2)
    }
    
    @EnableAudit
    entity Post {
      title String required
      content TextBlob required
      date Instant required
    }
    
    @EnableAudit
    entity Tag {
      name String required minlength(2)
    }
    
    relationship ManyToOne {
      Post{blog(name)} to Blog
    }
    
    relationship ManyToMany {
      Post{tag(name)} to Tag{entry}
    }

Is this an expected behavior?

**Comment by mshima** [comment]
Unfortunately won't work with jhipster v7.
This blueprint is written using new features that is not used by main generator v7. Once we switch to v8 it should work.

As workaround you can ignore everything except entities folders by creating a `.yo-resolve` file (something like this):
```
!src/{main,test}/java/my/package/{domain,rest,service}
```

**Comment by mshima** [comment]
jhipster 8 will pass the blueprint which entity to write.
