### ISSUE TITLE
Entity Audit Blueprint Blocking JDL Import Process

### ISSUE THREAD

**Issue by ArmelZy** [jhipster/generator-jhipster-entity-audit#217]
After installing the Entity Audit module and auditing all my entities, I encountered an error when attempting to update the main.jdl file of the application. Please refer to the attached screenshot for more details.

![audit error](https://github.com/jhipster/generator-jhipster-entity-audit/assets/40440649/a39f80de-94bc-4aec-b736-9a37aa4bfd15)

A simple workaround to resolve this issue is to remove the Entity Audit module information from the .yo-rc.json file.

![workaround](https://github.com/jhipster/generator-jhipster-entity-audit/assets/40440649/d2ee5c2e-b592-410f-b52f-09b8af95df0f)

After doing this, I was able to successfully import my updated JDL file.

INFO! No custom commands found within blueprint: generator-jhipster-entity-audit at ..\node_modules\generator-jhipster-entity-audit

        ΓûêΓûêΓòù ΓûêΓûêΓòù   ΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù   ΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù
        ΓûêΓûêΓòæ ΓûêΓûêΓòæ   ΓûêΓûêΓòæ ΓòÜΓòÉΓòÉΓûêΓûêΓòöΓòÉΓòÉΓò¥ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓûêΓûêΓòù ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓò¥ ΓòÜΓòÉΓòÉΓûêΓûêΓòöΓòÉΓòÉΓò¥ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓûêΓûêΓòù
        ΓûêΓûêΓòæ ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòæ    ΓûêΓûêΓòæ    ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥ ΓòÜΓûêΓûêΓûêΓûêΓûêΓòù     ΓûêΓûêΓòæ    ΓûêΓûêΓûêΓûêΓûêΓûêΓòù   ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥
  ΓûêΓûêΓòù   ΓûêΓûêΓòæ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓûêΓûêΓòæ    ΓûêΓûêΓòæ    ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓò¥   ΓòÜΓòÉΓòÉΓòÉΓûêΓûêΓòù    ΓûêΓûêΓòæ    ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓò¥   ΓûêΓûêΓòöΓòÉΓòÉΓûêΓûêΓòæ
  ΓòÜΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥ ΓûêΓûêΓòæ   ΓûêΓûêΓòæ ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓòæ       ΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥    ΓûêΓûêΓòæ    ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓòæ  ΓòÜΓûêΓûêΓòù
   ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥  ΓòÜΓòÉΓò¥   ΓòÜΓòÉΓò¥ ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ ΓòÜΓòÉΓò¥       ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥     ΓòÜΓòÉΓò¥    ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ ΓòÜΓòÉΓò¥   ΓòÜΓòÉΓò¥
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0

```
prismil@0.0.1-SNAPSHOT ...
+-- generator-jhipster-entity-audit@5.0.0
| `-- generator-jhipster@8.0.0 deduped
`-- generator-jhipster@8.0.0
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "Prismil",
    "blueprints": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "5.0.0"
      }
    ],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "zephyr",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1699087290401,
    "cypressAudit": true,
    "cypressCoverage": null,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "UserProfile",
      "UserPhoto"
    ],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0",
    "languages": [
      "fr",
      "en"
    ],
    "lastLiquibaseTimestamp": 1699087410000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "fr",
    "packageName": "test.go.appl",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "websocket:spring-websocket"
    ],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": "spring-websocket",
    "withAdminUi": true
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "javers",
    "auditPage": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

git version 2.37.2.windows.2

node: v18.18.2
npm: 9.8.1

Docker version 20.10.21, build baeda1f

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The User Profile entity.\n@author PRISMIL
 */
entity UserProfile {
  /**
   * registration number
   */
  registrationNumber String unique required pattern(/^\b\d{5}\b$/)
  /**
   * grade
   */
  grade Grade required
  /**
   * telephone main
   */
  telephoneMain String unique required pattern(/^\b\d{9}\b$/)
  /**
   * telephone secondary
   */
  telephoneSecondary String unique pattern(/^\b\d{8,16}\b$/)
  /**
   * sex
   */
  sex Sex required
  createdBy String
  createdDate Instant
  lastModifiedBy String
  lastModifiedDate Instant
}
/**
 * The User Photo entity.\n@author PRISMIL
 */
entity UserPhoto {
  /**
   * data
   */
  data ImageBlob required
  createdBy String
  createdDate Instant
  lastModifiedBy String
  lastModifiedDate Instant
}
enum Grade {
  O_COL,
  O_LT_COL,
  O_CE,
  O_CNE,
  O_LT,
  O_S_LT,
  SO_ACM,
  SO_A_C,
  SO_AT,
  SO_MDL_C,
  SO_MDL,
  MR_G_M,
  MR_GEND,
  MR_E_G
}
enum Sex {
  MALE,
  FEMALE
}

relationship OneToOne {
  @id
  UserProfile{user(login) required} to User with builtInEntity
  @id
  UserPhoto{user(login) required} to User with builtInEntity
}

paginate UserProfile, UserPhoto with pagination
service UserProfile, UserPhoto with serviceClass
search UserProfile, UserPhoto with no

</pre>
</details>

Please let me know if it is a real issue @deepu105 @mshima

**Comment by mshima** [comment]
Looks a bug, but we need reproduction steps.

**Comment by mshima** [comment]
Post your `jhipster info` output.

**Comment by ArmelZy** [comment]
@mshima Here is the output of the following command: `jhipster info > info.txt`


INFO! No custom commands found within blueprint: generator-jhipster-entity-audit at ..\node_modules\generator-jhipster-entity-audit

        ΓûêΓûêΓòù ΓûêΓûêΓòù   ΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù   ΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù
        ΓûêΓûêΓòæ ΓûêΓûêΓòæ   ΓûêΓûêΓòæ ΓòÜΓòÉΓòÉΓûêΓûêΓòöΓòÉΓòÉΓò¥ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓûêΓûêΓòù ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓò¥ ΓòÜΓòÉΓòÉΓûêΓûêΓòöΓòÉΓòÉΓò¥ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓûêΓûêΓòù
        ΓûêΓûêΓòæ ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòæ    ΓûêΓûêΓòæ    ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥ ΓòÜΓûêΓûêΓûêΓûêΓûêΓòù     ΓûêΓûêΓòæ    ΓûêΓûêΓûêΓûêΓûêΓûêΓòù   ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥
  ΓûêΓûêΓòù   ΓûêΓûêΓòæ ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓûêΓûêΓòæ    ΓûêΓûêΓòæ    ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓòÉΓò¥   ΓòÜΓòÉΓòÉΓòÉΓûêΓûêΓòù    ΓûêΓûêΓòæ    ΓûêΓûêΓòöΓòÉΓòÉΓòÉΓò¥   ΓûêΓûêΓòöΓòÉΓòÉΓûêΓûêΓòæ
  ΓòÜΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥ ΓûêΓûêΓòæ   ΓûêΓûêΓòæ ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓòæ       ΓûêΓûêΓûêΓûêΓûêΓûêΓòöΓò¥    ΓûêΓûêΓòæ    ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓòù ΓûêΓûêΓòæ  ΓòÜΓûêΓûêΓòù
   ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥  ΓòÜΓòÉΓò¥   ΓòÜΓòÉΓò¥ ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ ΓòÜΓòÉΓò¥       ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥     ΓòÜΓòÉΓò¥    ΓòÜΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓòÉΓò¥ ΓòÜΓòÉΓò¥   ΓòÜΓòÉΓò¥
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0


```
prismil@0.0.1-SNAPSHOT ...
+-- generator-jhipster-entity-audit@5.0.0
| `-- generator-jhipster@8.0.0 deduped
`-- generator-jhipster@8.0.0
```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "Prismil",
    "blueprints": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "5.0.0"
      }
    ],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "zephyr",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1699087290401,
    "cypressAudit": true,
    "cypressCoverage": null,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "UserProfile",
      "UserPhoto"
    ],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0",
    "languages": [
      "fr",
      "en"
    ],
    "lastLiquibaseTimestamp": 1699087410000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "fr",
    "packageName": "test.go.appl",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "websocket:spring-websocket"
    ],
    "serviceDiscoveryType": false,
    "testFrameworks": [
      "cypress"
    ],
    "websocket": "spring-websocket",
    "withAdminUi": true
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "javers",
    "auditPage": true
  }
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

git version 2.37.2.windows.2

node: v18.18.2
npm: 9.8.1

Docker version 20.10.21, build baeda1f

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The User Profile entity.\n@author PRISMIL
 */
entity UserProfile {
  /**
   * registration number
   */
  registrationNumber String unique required pattern(/^\b\d{5}\b$/)
  /**
   * grade
   */
  grade Grade required
  /**
   * telephone main
   */
  telephoneMain String unique required pattern(/^\b\d{9}\b$/)
  /**
   * telephone secondary
   */
  telephoneSecondary String unique pattern(/^\b\d{8,16}\b$/)
  /**
   * sex
   */
  sex Sex required
  createdBy String
  createdDate Instant
  lastModifiedBy String
  lastModifiedDate Instant
}
/**
 * The User Photo entity.\n@author PRISMIL
 */
entity UserPhoto {
  /**
   * data
   */
  data ImageBlob required
  createdBy String
  createdDate Instant
  lastModifiedBy String
  lastModifiedDate Instant
}
enum Grade {
  O_COL,
  O_LT_COL,
  O_CE,
  O_CNE,
  O_LT,
  O_S_LT,
  SO_ACM,
  SO_A_C,
  SO_AT,
  SO_MDL_C,
  SO_MDL,
  MR_G_M,
  MR_GEND,
  MR_E_G
}
enum Sex {
  MALE,
  FEMALE
}

relationship OneToOne {
  @id
  UserProfile{user(login) required} to User with builtInEntity
  @id
  UserPhoto{user(login) required} to User with builtInEntity
}

paginate UserProfile, UserPhoto with pagination
service UserProfile, UserPhoto with serviceClass
search UserProfile, UserPhoto with no

</pre>
</details>
