### ISSUE TITLE
 generator-jhipster-entity-audit resets my custom existng code and configuration into the initial state generated by jhipster

### ISSUE THREAD

**Issue by artyomsv** [jhipster/generator-jhipster-entity-audit#282]
I have a new Jhipster application build with generator version 8.7.1 on windows 10

<details>
<summary>.yo-rc.json</summary>

```json
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "SimpleApplication",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "clientTestFrameworks": [],
    "clientTheme": "darkly",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1725573484341,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["SimpleEntity"],
    "feignClient": null,
    "jhipsterVersion": "8.7.1",
    "languages": ["en", "ru"],
    "lastLiquibaseTimestamp": 1729886881000,
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.stukans.buddy",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [],
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "syncUserWithIdp": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}
```
</details>

<details>
<summary>entities.jdl</summary>

```jdl
entity SimpleEntity {
  id UUID
}

```
</details>

The problem is when JDL entities are created and I want to introduce entity auditing I'm executing `jhipster-entity-audit` command all existing files (created by hipster) are being reverted to their initial state (for example some Java class, pom.xml, logback configuration, application.yaml files etc.), so I have to go through 60+ files manually and check what exactly was reverted and change it back to my code. This takes time and is not very convenient.

In the executor log I see this message "So we assume this is application regeneration.":
<details>
<summary>entities.jdl</summary>

```
Run `npm audit` for details.
     info Found .yo-rc.json in Git from E:/Projects/JHipster/simple-application. So we assume this is application regeneration. Therefore automatic Git commit is not done. You can do Git commit manually.
✔ Spring Boot application generated successfully.
  Run your Spring Boot application:
  ./mvnw (mvnw if using Windows Command Prompt)
✔ React application generated successfully.
  Start your Webpack development server with:
  npm start


Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

```
</details>

Is this the default behavior, or am I doing something wrong?

Thanks in advance!

**Comment by mshima** [comment]
This is the default behavior every jhipster generation will always generate the full project.

To help migrations you should try avoid changing generated files by adding additional files with customizations:
https://www.jhipster.tech/tips/035_tip_combine_generation_and_custom_code.html.

Use `jhipster upgrade` or [jhipster-migrate](https://github.com/jhipster/generator-jhipster-migrate) to apply changes.
Something like:
```sh
jhipster-migrate --target-cli-options "--blueprints entity-audit"
```
