### ISSUE TITLE
How to make entity audit work with JDL?

### ISSUE THREAD

**Issue by snapshotleisure** [jhipster/generator-jhipster-entity-audit#288]
Hi, Sorry if this is mentioned somewhere, however I have been trying to find an example on how to get entity audit work with a JDL file however I have been unable to find it anywhere.

I have seen some mentions of annotating an entity with @EnableAudit, however i see this just adds enableAudit: true into the annotations key for the json file. 

Afterwards when i try to run the command:
jhipster jdl .\entities.jdl --incremental-changelog --skip-fake-data --blueprints entity-audit

I don't see my entity having the extend AbstractAuditingEntity.

Is it actually supported to have a entity be audited using a JDL file? or it will require manual adjustments after the JDL import?

Thanks!

**Comment by snapshotleisure** [comment]
Hi @mshima,

Sorry to bother, was wondering if you are able to shed any light to this?

Thanks

**Comment by mshima** [comment]
Our sample uses `@EnableAudit`:
https://github.com/jhipster/generator-jhipster-entity-audit/blob/main/.blueprint/generate-sample/templates/samples/postgresql-mvc-jwt.jdl

**Comment by snapshotleisure** [comment]
Thank you much appreciated!

**Comment by snapshotleisure** [comment]
Hi @mshima 
I used the @EnableAudit annotation and in the Entity JSON File, I get
`"annotations": {
    "changelogDate": "20241215001546",
    "enableAudit": true
  },`

I have seperated my jdl into two files, one is for app.jdl and the other one is entity.jdl 

I try to create the entity with the following command:
jhipster jdl .\business-manager-entities.jdl --incremental-changelog --blueprints entity-audit

However the entity doesn't have any of the audit properties on it.

Is there anything else I need to configure to make this work? Do I need the include the app.jdl file as well when generating the entity?

**Comment by mshima** [comment]
`jhipster jdl .\business-manager-entities.jdl --incremental-changelog --blueprints entity-audit --audit-framework javers`
Or
`jhipster-entity-audit jdl .\business-manager-entities.jdl --incremental-changelog --audit-framework javers`

You can choose `custom` audit-framework too.

**Comment by snapshotleisure** [comment]
Hi @mshima 

Thanks for that, I got a little bit further with the updated command above. I can see some of the audit code being generated as in the @JaversSpringDataAuditable being added to my repository,

However I get the following error when querying the entity
ERROR: column ak1_0.created_by does not exist

I checked the liquidbase file below and don't see the created_by, created_date, last_modified_by, last_modified_date columns being created.
20241216110641_added_entity_ApiKey.xml

Am I missing something?

Please let me know if any further information is required.

Sorry this is my first time doing JDL, I am wanting to learn it. Previously I did a project with just the CLI to create entities and the audit works. However I wanted to learn JDL and it seems to make things simpler.

Thanks

**Comment by ZiyaErcanErdem** [comment]
Hi @mshima and @snapshotleisure, I'm also facing same issue on latest release. IMO, entity update liquibase template for audit fields is missing in both javers and custom audit frameworks option.

**Comment by mshima** [comment]
Looks related to incremental changelog.

I cannot help much without reproduction steps an samples.

**Comment by snapshotleisure** [comment]
Hi @mshima 
I have created a repo with my entities and applications jdl here: https://github.com/snapshotleisure/generator-jhipster-audit-jdl-issue

I have used the following commands, however they all don't generate the created_by, created_date, last_modified_by, last_modified_date fields:
- jhipster jdl .\business-manager-app.jdl .\business-manager-entities.jdl --blueprints entity-audit --audit-framework javers
- jhipster jdl .\business-manager-app.jdl .\business-manager-entities.jdl --blueprints entity-audit --audit-framework custom
- jhipster jdl .\business-manager-app.jdl .\business-manager-entities.jdl --incremental-changelog --blueprints entity-audit --audit-framework javers
- jhipster jdl .\business-manager-app.jdl .\business-manager-entities.jdl --incremental-changelog --blueprints entity-audit --audit-framework custom

I am on Jhipster and entity-audit 8.7.3 on Windows

**Comment by mverwaerde** [comment]
Hey @mshima , thanks for your work on this blueprints. 

Can you add this example commands on readme on jdl parts. It will be easier to find how to generate from jdl 

`jhipster-entity-audit jdl .\my-jdl.jdl --incremental-changelog --audit-framework javers
`
